name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.14"]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: py2vega
        create-args: >-
          python=${{ matrix.python-version }}
          pytest
          pytest-cov
          flake8

    - name: Install py2vega
      run: pip install -e .

    - name: Test flake8
      run: flake8 py2vega --ignore=E501,W504,W503

    - name: Run pytest
      run: pytest --cov-report term-missing --cov=py2vega.main test
